COUNTRY_CHOICES = [
    ('Argentina', 'Argentina'),
    ('Australia', 'Australia'),
    ('Azerbaijan', 'Azerbaijan'),
    ('Bahrain', 'Bahrain'),
    ('Brazil', 'Brazil'),
    ('Canada', 'Canada'),
    ('Switzerland', 'Switzerland'),
    ('Chile', 'Chile'),
    ('China', 'China'),
    ('Colombia', 'Colombia'),
    ('Costa', 'Costa'),
    ('Rica', 'Rica'),
    ('Czech Republic', 'Czech Republic'),
    ('Denmark', 'Denmark'),
    ('Egypt', 'Egypt'),
    ('Euro area', 'Euro area'),
    ('Britain', 'Britain'),
    ('Guatemala', 'Guatemala'),
    ('Hong Kong', 'Hong Kong'),
    ('Honduras', 'Honduras'),
    ('Croatia', 'Croatia'),
    ('Hungary', 'Hungary'),
    ('Indonesia', 'Indonesia'),
    ('India', 'India'),
    ('Israel', 'Israel'),
    ('Jordan', 'Jordan'),
    ('Japan', 'Japan'),
    ('South Korea', 'South Korea'),
    ('Kuwait', 'Kuwait'),
    ('Lebanon', 'Lebanon'),
    ('Sri Lanka', 'Sri Lanka'),
    ('Moldova', 'Moldova'),
    ('Mexico', 'Mexico'),
    ('Malaysia', 'Malaysia'),
    ('Nicaragua', 'Nicaragua'),
    ('New Zealand', 'New Zealand'),
    ('Pakistan', 'Pakistan'),
    ('Philippines', 'Philippines'),
    ('Poland', 'Poland'),
    ('Qatar', 'Qatar'),
    ('Romania', 'Romania'),
    ('Russia', 'Russia'),
    ('Saudi Arabia', 'Saudi Arabia'),
    ('Singapore', 'Singapore'),
    ('Sweden', 'Sweden'),
    ('Thailand', 'Thailand'),
    ('Turkey', 'Turkey'),
    ('Taiwan', 'Taiwan'),
    ('United Arab Emirates', 'United Arab Emirates'),
    ('Ukraine', 'Ukraine'),
    ('Uruguay', 'Uruguay'),
    ('United States', 'United States'),
    ('Vietnam', 'Vietnam'),
    ('South Africa', 'South Africa'),
]
