# Generated by Django 3.1.4 on 2021-01-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigMacIndexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('iso_a3', models.CharField(max_length=5)),
                ('currency_code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('local_price', models.FloatField(max_length=100)),
                ('dollar_ex', models.FloatField(max_length=100)),
                ('USD_raw', models.FloatField(max_length=100)),
                ('EUR_raw', models.FloatField(max_length=100)),
                ('GBP_raw', models.FloatField(max_length=100)),
                ('JPY_raw', models.FloatField(max_length=100)),
                ('CNY_raw', models.FloatField(max_length=100)),
                ('GDP_dollar', models.FloatField(max_length=100)),
                ('adj_price', models.FloatField(max_length=100)),
                ('USD_adjusted', models.FloatField(max_length=100)),
                ('EUR_adjusted', models.FloatField(max_length=100)),
                ('GBP_adjusted', models.FloatField(max_length=100)),
                ('JPY_adjusted', models.FloatField(max_length=100)),
                ('CNY_adjusted', models.FloatField(max_length=100)),
            ],
        ),
    ]
